### ISSUE TITLE
Unable to inject into Forge 1.8.9

### ISSUE THREAD

**Issue by LCMCat** [Kolhax/Vape-V4-Source#1]
My Forge Version is 11.15.1.2318

**Comment by CMCat-Xicheng** [comment]
Forge 11.14.4.1563 is not up to date

**Comment by TIMER-err** [comment]
me too

**Comment by Kolhax** [comment]
Look at the new readme this version was just a dump of known stuff on vape v4, the link to the full cracked vape is in the readme.md file
