### ISSUE TITLE
How do you build it with broken codes

### ISSUE THREAD

**Issue by cubewhy** [Kolhax/Vape-V4-Source#2]
![image](https://github.com/Kolhax/Vape-V4-Source/assets/61075476/4db37094-f44b-425a-99a4-789b8ba78a02)

I think your release is other's vape crack, LOL

Last time I dump vape client, it was 1000+ classes, but yours only have 14 classes

**Comment by PlayMcBKuwu** [comment]
I tried to build and I got a notice says '`Dimples#1337` wants to control your PC'

**Comment by cubewhy** [comment]
6

**Comment by Kolhax** [comment]
Look ReadME.md i just updated it, since peoples dint knew, this repo is just a dump the full crack will be posted soon since https://kepar.ml/ is not online anymore
